version: '3.3'

services:
  birthday-nuxt:
    container_name: "birthday-nuxt"
    build: ./docker/nuxt
    ports:
      - 3000:3000
    volumes:
      - ./nuxt:/app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
